highlighter: rouge

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
  math_engine: MathJax

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

paginate: 7
paginate_path: "page:num"
layout: post
permalink: /:categories/:title
excerpt_separator: "[-----]"

url: # Required: replace this with your domain
name: SRDoctor # Required: will be displayed on every page's header
title: 中国汽研异响识别系统 # Required: site's default title
shout: # Required: **TWO** lines, will be displayed on page's header.
  - 中国汽车工程研究院
description: "SR-Doctor" # Required

disqus:
  comments: true # Global toggle on/off disqus comment
  shortname: unifreak # Required if you use disqus. Repalce with your disqus shortname here

google_analytics:
  id: "" # Required if you use google analytics. Replace with your tracking id here

collections: # Define post series here
  demo_series:
    output: true
  demo_series_2:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "post"